# nginx configuration for Django project
upstream django_app {
    server web:8000;
}

server {
    listen 80;
    server_name 8.161.226.168 8.130.51.93 localhost;

    location /static/ {
        alias /opt/services/djangoapp/src/static/;
    }

    location /media/ {
        alias /opt/services/djangoapp/src/media/;
    }

    location / {
        proxy_pass http://django_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
