# Generated by Django 5.2.14 on 2026-05-25 11:00

import django.db.models.deletion
import django.utils.timezone
import froala_editor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MyNew",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="标题")),
                ("description", froala_editor.fields.FroalaField(verbose_name="内容")),
                (
                    "newType",
                    models.CharField(
                        choices=[
                            ("企业新闻", "企业新闻"),
                            ("行业新闻", "行业新闻"),
                            ("通知公告", "通知公告"),
                        ],
                        max_length=50,
                        verbose_name="新闻类型",
                    ),
                ),
                (
                    "publishDate",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="发布时间"
                    ),
                ),
                (
                    "views",
                    models.PositiveIntegerField(default=0, verbose_name="浏览量"),
                ),
            ],
            options={
                "verbose_name": "新闻",
                "verbose_name_plural": "新闻",
                "ordering": ("-publishDate",),
            },
        ),
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=12, verbose_name="姓名")),
                ("address", models.CharField(max_length=60, verbose_name="地址")),
                ("age", models.IntegerField(verbose_name="年龄")),
                ("tel", models.CharField(max_length=14, verbose_name="电话")),
                ("memo", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "学生",
                "verbose_name_plural": "学生",
            },
        ),
        migrations.CreateModel(
            name="useraccount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accountname",
                    models.CharField(default="", max_length=20, verbose_name="姓名"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户账户",
                "verbose_name_plural": "用户账户",
            },
        ),
    ]
