"""
Django settings for djangoProject project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-krhxb&&hfm=@vtlhkr&xnkrwgcn$!7*f6t&i=y5h5lhsv8rrd+"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['8.161.226.168', '8.130.51.93', 'localhost', '127.0.0.1']

# ==================== 部署安全配置（端口替换为你自己的） ====================
ALLOWED_ORIGINS = ['http://8.161.226.168:9207', 'http://8.130.51.93:9207']
CSRF_TRUSTED_ORIGINS = ALLOWED_ORIGINS.copy()
CSRF_COOKIE_SECURE = False


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "db",
    "captcha",
    "froala_editor",
    "haystack",
    "widget_tweaks",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "djangoProject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "djangoProject.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "zh-hans"
TIME_ZONE = "Asia/Shanghai"

#TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

import os

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'media'),
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# ==================== 邮件发送配置 ====================
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 25
EMAIL_HOST_USER = '2407373665@qq.com'
EMAIL_HOST_PASSWORD = 'laimpfxbpavadhhg'         # 授权码（需替换为实际授权码）
EMAIL_USE_TLS = True
EMAIL_FROM = '2407373665@qq.com'

# ==================== Django Simple Captcha 配置 ====================
CAPTCHA_FONT_SIZE = 30
CAPTCHA_CHALLENGE_FUNCT = 'member.capta_func.random_digit_challenge'

# ==================== Froala Editor 配置 ====================
FROALA_EDITOR_PLUGINS = (
    'align', 'char_counter', 'code_beautifier', 'code_view', 'colors',
    'draggable', 'emoticons', 'entities', 'file', 'font_family', 'font_size',
    'fullscreen', 'image_manager', 'image', 'inline_style', 'line_breaker',
    'link', 'lists', 'paragraph_format', 'paragraph_style', 'quick_insert',
    'quote', 'save', 'table', 'url', 'video',
)

# ==================== Django Haystack 全文搜索配置 ====================
HAYSTACK_CONNECTIONS = {
    'default': {
        # 使用项目根目录下已集成 jieba 中文分词的 whoosh 后端
        'ENGINE': 'whoosh_backend.WhooshEngine',
        'PATH': os.path.join(os.path.dirname(__file__), 'whoosh_index'),
    },
}
HAYSTACK_SEARCH_RESULTS_PER_PAGE = 10
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'
